version: "3.7"

services:
  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - frontend

  client:
    container_name: client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend/:/app"
      - "/app/node_modules"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
