version: "3.8"

volumes:
  mysql_data:
  redisdata:
  build_folder:

services:
  mysqldb:
    build: ./backend/db
    env_file:
      - "./backend/db/db.env"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend/backend
    command: >
      bash -c "python wait_mysql.py &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py loaddata fixture.json &&
               gunicorn backend.wsgi:application --bind 0.0.0.0:8080" &&
               
    ports:
      - "8080:8080"
    volumes:
      - ./backend/backend:/app
    depends_on:
      - mysqldb
      - redis
    links:
      - mysqldb

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - 'redisdata:/data'

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - build_folder:/var/www/app
    depends_on:
      - backend
      - client

  client:
    container_name: client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app
      - build_folder:/app/build
    tty: true

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "5672:5672" # Default Port
      - "15672:15672" # For UI
    expose:
      - "15672"

  celery_worker:
    container_name: celery_worker
    build:
      context: ./backend/backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/app
    ports: []
    depends_on:
      - rabbitmq
      - redis
      - backend
    environment:
      - C_FORCE_ROOT=true
    command: sh -c "python wait_mysql.py &&
                    celery -A backend worker --loglevel=info"